# .github/workflows/ci-cd.yaml
name: CI/CD - WAS (SHA tracked)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

concurrency:
  group: was-cicd
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout WAS app repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push image (SHA + latest)
        env:
          ECR_REGISTRY: 043902793737.dkr.ecr.ap-northeast-2.amazonaws.com
          ECR_REPO: ksh-was/flask-app
          SHA: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:$SHA -t $ECR_REGISTRY/$ECR_REPO:latest .
          docker push $ECR_REGISTRY/$ECR_REPO:$SHA
          docker push $ECR_REGISTRY/$ECR_REPO:latest
          echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPO:$SHA" >> $GITHUB_ENV

      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: soloud1025/was-manifests
          path: was-manifests
          token: ${{ secrets.GH_PAT }}

      - name: Install yq (v4)
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          yq --version

      - name: Patch image in final-app.yaml (only WAS container)
        env:
          IMAGE_URI: ${{ env.IMAGE_URI }}
        run: |
          cd was-manifests
          yq -i '
            (.spec.template.spec.containers[] | select(.name == "was") | .image) = strenv(IMAGE_URI)
          ' final-app.yaml

      - name: Commit & Push manifest change
        run: |
          cd was-manifests
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add final-app.yaml
          git commit -m "chore(was): deploy $IMAGE_URI" || echo "no changes"
          git push

